const icon = (name) => `<i class="sidebar-icon ph ph-${name}" aria-hidden="true"></i>`;
export const modules = {
  home:{id:'home',label:'App Home',shortLabel:'Home',theme:'home',bannerTitle:'Welcome',bannerEyebrow:'Ummiby Companion',description:'Your companion for Qur’an, duaa, memorization, Ramadan, and daily worship.',icon:icon('house'),navigation:[{label:'App Home',route:'/home'}]},
  quran:{id:'quran',label:'Qur’an',shortLabel:'Qur’an',theme:'quran',bannerTitle:'Read, reflect, and continue',bannerEyebrow:'Qur’an',description:'Reading journeys, surah reading, memorization, and trusted study resources.',icon:icon('book-open-text'),navigation:[{label:'Qur’an Home',route:'/quran'},{label:'Reading Journeys',route:'/quran/journeys'},{label:'Special Readings',route:'/quran/special-readings'},{label:'Memorization',route:'/quran/memorization'}]},
  duaa:{id:'duaa',label:'Duaa',shortLabel:'Duaa',theme:'duaa',bannerTitle:'Call upon Allah with hope',bannerEyebrow:'Duaa',description:'Daily collections, calm reading, and gentle consistency tracking.',icon:icon('heart'),navigation:[{label:'Duaa Home',route:'/duaa'},{label:'Morning',route:'/duaa/morning'},{label:'Evening',route:'/duaa/evening'},{label:'Before Sleep',route:'/duaa/sleep'},{label:'Collections',route:'/duaa/collections'},{label:'Memorization',route:'/duaa/memorization'},{label:'History',route:'/duaa/history'}]},
  names:{id:'names',label:'Names of Allah',shortLabel:'Names of Allah',theme:'names',bannerTitle:'Learn the beautiful Names',bannerEyebrow:'Names of Allah',description:'A dedicated place to learn, review, and reflect upon the Names of Allah.',icon:icon('star'),navigation:[{label:'Names Home',route:'/names'},{label:'All Names',route:'/names/all'},{label:'Study',route:'/names/study'},{label:'Review',route:'/names/review'}]},
  prayer:{id:'prayer',label:'Prayer',shortLabel:'Prayer',theme:'prayer',bannerTitle:'Learn the prayer from beginning to end',bannerEyebrow:'Prayer',description:'Authentic guidance, practical resources, and future prayer-time tools in one focused place.',icon:icon('mosque'),navigation:[{label:'Prayer Home',route:'/prayer'}]},
  fasting:{id:'fasting',label:'Fasting',shortLabel:'Fasting',theme:'fasting',bannerTitle:'Keep a thoughtful record of your fasts',bannerEyebrow:'Fasting',description:'Year-round fasting records, authentic guidance, and a clear history beyond Ramadan.',icon:icon('sun-horizon'),navigation:[{label:'Fasting Home',route:'/fasting'}]},
  ramadan:{id:'ramadan',label:'Ramadan',shortLabel:'Ramadan',theme:'ramadan',bannerTitle:'Keep the month close',bannerEyebrow:'Ramadan Central',description:'Fasting records, Qur’an reading, duaa, and yearly Ramadan history.',icon:icon('moon'),navigation:[{label:'Ramadan Home',route:'/ramadan'},{label:'Reading Journey',route:'/ramadan/reading'},{label:'Fasting',route:'/ramadan/fasting'},{label:'Duaa Library',route:'/ramadan/duaa'},{label:'History',route:'/ramadan/history'}]},
  settings:{id:'settings',label:'Settings',shortLabel:'Settings',theme:'settings',bannerTitle:'Make the companion yours',bannerEyebrow:'Settings',description:'Account, appearance, reading preferences, and data controls.',icon:icon('gear'),navigation:[{label:'Settings Home',route:'/settings'},{label:'Account',route:'/settings/account'},{label:'Preferences',route:'/settings/preferences'},{label:'Data',route:'/settings/data'}]}
};
export const sidebarOrder=['home','quran','duaa','names','prayer','fasting','ramadan','settings'];
export function moduleForPath(pathname){ const first=pathname.split('/').filter(Boolean)[0]||'home'; return modules[first]||modules.home; }
