const icon = (name) => `<i class="sidebar-icon ph ph-${name}" aria-hidden="true"></i>`;
export const modules = {
  home:{id:'home',label:'App Home',shortLabel:'Home',theme:'home',bannerTitle:'Welcome',bannerEyebrow:'Ummiby Companion',description:'Your companion for Qur’an, duaa, memorization, Ramadan, and daily worship.',icon:icon('house'),navigation:[{label:'App Home',route:'/home'}]},
  quran:{id:'quran',label:'Qur’an',shortLabel:'Qur’an',theme:'quran',bannerTitle:'A Daily Companion to the Qur’an',bannerEyebrow:'Qur’an',description:'A peaceful place to read, reflect, and memorize the Qur’an.',icon:icon('book-open-text'),navigation:[{label:'Home',route:'/quran'},{label:'Reading Journeys',route:'/quran/journeys'},{label:'Qur’an Navigator',route:'/quran/navigator'},{label:'Featured Readings',route:'/quran/featured-readings'},{label:'Memorization',route:'/quran/memorization'},{label:'Reading History',route:'/quran/history'},{label:'Settings',route:'/quran/settings'}]},
  duaa:{id:'duaa',label:'Duaa',shortLabel:'Duaa',theme:'duaa',bannerTitle:'Call upon Allah with hope',bannerEyebrow:'Duaa',description:'Daily collections, calm reading, and gentle consistency tracking.',icon:icon('heart'),navigation:[{label:'Duaa Home',route:'/duaa'},{label:'Morning',route:'/duaa/morning'},{label:'Evening',route:'/duaa/evening'},{label:'Before Sleep',route:'/duaa/sleep'},{label:'Collections',route:'/duaa/collections'},{label:'Memorization',route:'/duaa/memorization'},{label:'History',route:'/duaa/history'}]},
  names:{id:'names',label:'Names of Allah',shortLabel:'Names of Allah',theme:'names',bannerTitle:'Know Allah Through His Beautiful Names',bannerEyebrow:'Names of Allah',description:'A dedicated place to learn, review, and reflect upon the Names of Allah.',icon:icon('star'),navigation:[{label:'Home',route:'/names'},{label:'Explore',route:'/names/explore'},{label:'Learn',route:'/names/learn'},{label:'Review',route:'/names/review'},{label:'Favorites',route:'/names/favorites'},{label:'About',route:'/names/about'}]},
  prayer:{id:'prayer',label:'Prayer Companion',shortLabel:'Prayer',theme:'prayer',bannerTitle:'A Guided Companion for the Prayer',bannerEyebrow:'Prayer Companion',description:'Learn the prayer, study wudu, explore supplications, and build steady understanding in one guided place.',icon:icon('mosque'),navigation:[{label:'Prayer Home',route:'/prayer'},{label:'Daily Prayers',route:'/prayer/daily-prayers'},{label:'Sunnah & Voluntary',route:'/prayer/sunnah'},{label:'Learn the Prayer',route:'/prayer/learn'},{label:'Wudu',route:'/prayer/wudu'},{label:'Duaa Library',route:'/prayer/duaa'},{label:'Knowledge',route:'/prayer/knowledge'},{label:'My Progress',route:'/prayer/progress'}]},
  fasting:{id:'fasting',label:'Fasting Companion',shortLabel:'Fasting',theme:'fasting',bannerTitle:'A Lifelong Companion for Fasting',bannerEyebrow:'Fasting Companion',description:'Learn the worship of fasting, record voluntary and make-up fasts, and see Ramadan within one lifelong history.',icon:icon('sun-horizon'),navigation:[{label:'Fasting Home',route:'/fasting'},{label:'Learn About Fasting',route:'/fasting/learn'},{label:'Sunnah Fasts',route:'/fasting/sunnah'},{label:'Fasting History',route:'/fasting/history'},{label:'Make-up Fasts',route:'/fasting/makeup'},{label:'Fasting Library',route:'/fasting/library'},{label:'Settings',route:'/fasting/settings'}]},
  ramadan:{id:'ramadan',label:'Ramadan',shortLabel:'Ramadan',theme:'ramadan',bannerTitle:'Keep the month close',bannerEyebrow:'Ramadan Central',description:'Fasting records, Qur’an reading, duaa, and yearly Ramadan history.',icon:icon('moon'),navigation:[{label:'Ramadan Home',route:'/ramadan'},{label:'Reading Journey',route:'/ramadan/reading'},{label:'Fasting',route:'/ramadan/fasting'},{label:'Duaa Library',route:'/ramadan/duaa'},{label:'History',route:'/ramadan/history'}]},
  settings:{id:'settings',label:'Settings',shortLabel:'Settings',theme:'settings',bannerTitle:'Make the companion yours',bannerEyebrow:'Settings',description:'Account, appearance, reading preferences, and data controls.',icon:icon('gear'),navigation:[{label:'Settings Home',route:'/settings'},{label:'Account',route:'/settings/account'},{label:'Preferences',route:'/settings/preferences'},{label:'Data',route:'/settings/data'}]}
};
export const sidebarOrder=['home','quran','duaa','names','prayer','fasting','ramadan','settings'];
export function moduleForPath(pathname){ const first=pathname.split('/').filter(Boolean)[0]||'home'; return modules[first]||modules.home; }
